// <auto-generated />
using ForIntership.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ForIntership.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ForIntership.Models.Bug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CriticalityName");

                    b.Property<DateTime>("Date");

                    b.Property<string>("FullDescr");

                    b.Property<string>("ShortDescr");

                    b.Property<string>("StatusName");

                    b.Property<string>("UrgencyName");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CriticalityName");

                    b.HasIndex("StatusName");

                    b.HasIndex("UrgencyName");

                    b.HasIndex("UserId");

                    b.ToTable("Bugs");
                });

            modelBuilder.Entity("ForIntership.Models.Criticality", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Name");

                    b.ToTable("Criticalitys");
                });

            modelBuilder.Entity("ForIntership.Models.History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Action");

                    b.Property<int?>("BugId");

                    b.Property<string>("Comment");

                    b.Property<DateTime>("Date");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("BugId");

                    b.HasIndex("UserId");

                    b.ToTable("Historys");
                });

            modelBuilder.Entity("ForIntership.Models.Status", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Name");

                    b.ToTable("Statuss");
                });

            modelBuilder.Entity("ForIntership.Models.Urgency", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Name");

                    b.ToTable("Urgencys");
                });

            modelBuilder.Entity("ForIntership.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("Surname");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ForIntership.Models.Bug", b =>
                {
                    b.HasOne("ForIntership.Models.Criticality", "Criticality")
                        .WithMany()
                        .HasForeignKey("CriticalityName");

                    b.HasOne("ForIntership.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusName");

                    b.HasOne("ForIntership.Models.Urgency", "Urgency")
                        .WithMany()
                        .HasForeignKey("UrgencyName");

                    b.HasOne("ForIntership.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ForIntership.Models.History", b =>
                {
                    b.HasOne("ForIntership.Models.Bug")
                        .WithMany("histories")
                        .HasForeignKey("BugId");

                    b.HasOne("ForIntership.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
